[package]
name = "slingshot-agent"
description = "The Agent side of Slingshot: the daemon on the powerful machine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
slingshot-core = { path = "../slingshot-core", version = "0.1.0" }
anyhow = { workspace = true }
iroh = { workspace = true }
directories = { workspace = true }
libc = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shell-words = { workspace = true }
sysinfo = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
